name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: eventmarrakech
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, pdo_mysql
        coverage: none

    - name: Copy .env
      run: cp .env.example .env

    - name: Update .env for CI
      run: |
        sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
        sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/' .env
        sed -i 's/DB_PASSWORD=.*/DB_PASSWORD= /' .env
        sed -i 's/DB_DATABASE=.*/DB_DATABASE=eventmarrakech/' .env

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist

    - name: Generate app key
      run: php artisan key:generate

    - name: Wait for MySQL
      run: |
        for i in {1..20}; do
          nc -z 127.0.0.1 3306 && echo "MySQL is up!" && break
          echo "Waiting for MySQL... ($i)"
          sleep 3
        done

    - name: Run migrations
      run: php artisan migrate:fresh --force

    - name: Run tests
      run: php artisan test
